# Generated by Django 5.1.7 on 2025-04-02 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('contact', models.IntegerField()),
                ('doctor_email', models.EmailField(max_length=254)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('addittional_information', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appointment_images/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
