# Generated by Django 5.1.7 on 2025-04-28 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('patient_age', models.PositiveIntegerField(blank=True)),
                ('patient_email', models.EmailField(blank=True, max_length=254)),
                ('patient_number', models.CharField(blank=True, max_length=15)),
                ('disease', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, max_length=50, null=True)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('addittional_information', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='appointment_images/')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_requests', to='doctor.doctorprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='app.patientprofile')),
            ],
        ),
    ]
