# Generated by Django 5.1.7 on 2025-04-02 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='doctor_email',
        ),
    ]
