# Generated by Django 5.1.7 on 2025-04-06 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_patient_age_appointment_patient_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='phone_number',
            new_name='patient_number',
        ),
    ]
