# Generated by Django 5.1.7 on 2025-04-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='contact_number',
            field=models.CharField(max_length=22),
        ),
    ]
